THEMES = {
    "dark": {
        "bg": "#0a0a0a",
        "surface": "#141414",
        "surface2": "#1e1e1e",
        "surface3": "#2a2a2a",
        "border": "#363636",
        "accent": "#ff6b35",
        "accent_dim": "#cc5529",
        "accent_hover": "#ff8555",
        "green": "#4ade80",
        "yellow": "#facc15",
        "red": "#f87171",
        "text": "#f0f0f0",
        "text_dim": "#a0a0a0",
        "text_muted": "#6a6a6a",
        "entry_bg": "#1a1a1a",
        "entry_fg": "#f0f0f0",
    },
    "light": {
        "bg": "#f5f3f0",
        "surface": "#ffffff",
        "surface2": "#f0ede8",
        "surface3": "#e5e2dd",
        "border": "#ddd8d0",
        "accent": "#ff6b35",
        "accent_dim": "#e55a28",
        "accent_hover": "#ff7b4a",
        "green": "#16a34a",
        "yellow": "#ca8a04",
        "red": "#dc2626",
        "text": "#1a1a1a",
        "text_dim": "#666666",
        "text_muted": "#aaaaaa",
        "entry_bg": "#f8f6f3",
        "entry_fg": "#1a1a1a",
    },
}
